Repository CBIIT/bento-frontend, pull requests merged in 2020-11, with the labels that each got.

#208 Fixed styles for caseDetails page.
  src/bento/caseDetailData.js
  src/components/GridWithFooter/GridView.js
  src/pages/caseDetail/caseDetailView.js
  src/themes/dark.js
  src/themes/light.js
Labels: ✅ Ready for Merge

#214 Fixed armsDetails Page button styles missing bug.
  src/bento/armDetailData.js
  src/pages/armDetail/armDetailView.js
Labels: bug, ✅ Ready for Merge

#207 Added settings so show pagination on top in Dashboard.
  src/bento/dashboardTabData.js
  src/utils/tables.js
Labels: ✅ Ready for Merge

#213 Moved widgets to bento-components
  src/components/Widgets/PieCharts/CustomActiveDonut/CustomActiveDonutController.js
  src/components/Widgets/PieCharts/CustomActiveDonut/CustomActiveDonutView.js
  src/components/Widgets/PieCharts/Donut/DonutController.js
  src/components/Widgets/PieCharts/Donut/DonutView.js
  src/components/Widgets/PieCharts/ProgramSunburst/ProgramSunburstController.js
  src/components/Widgets/PieCharts/ProgramSunburst/ProgramSunburstView.js
  src/pages/armDetail/armDetailView.js
  src/pages/dashboard/dashboard.js
  src/pages/dashboardTab/dashboard.js
  src/pages/programDetail/programDetailView.js
  src/utils/colors.js
Labels: ✅ Ready for Merge

#228 adding title Location and Alignments for Widgets.
  src/pages/armDetail/armDetailView.js
  src/pages/dashboard/dashboard.js
  src/pages/dashboardTab/dashboard.js
  src/pages/programDetail/programDetailView.js
Labels: ✅ Ready for Merge

#224 Keep users selection persistent even after server-side pagination
  package-lock.json
  public/injectEnv.js
  src/bento/dashboardTabData.js
  src/components/Layout/LayoutView.js
  src/components/PropertySubsection/armDetailSubsection.js
  src/components/PropertySubsection/caseDetailSubsection.js
  src/components/SideBar/SideBarView.js
  src/components/Stats/pageSpecificStatsController.js
  src/components/serverPaginatedTable/serverPaginatedTable.js
  src/pages/armDetail/armDetailView.js
  src/pages/caseDetail/caseDetailView.js
  src/pages/dashboard/caseTable/caseView.js
  src/pages/dashboard/dashboardState.js
  src/pages/dashboardTab/components/tabController.js
  src/pages/dashboardTab/components/tabFooter.js
  src/pages/dashboardTab/components/tabView.js
  src/pages/dashboardTab/store/dashboardReducer.js
  src/pages/fileCentricCart/cartView.js
  src/pages/landing/landingView.js
  src/pages/programDetail/programDetailView.js
  src/pages/programs/programsView.js
  src/pages/selectedCases/customFooter.js
  src/pages/selectedCases/selectedCasesController.js
  src/pages/selectedCases/selectedCasesState.js
  src/pages/selectedCases/selectedCasesView.js
  src/pages/selectedFiles/customFooter.js
  src/pages/selectedFiles/selectedFilesController.js
  src/pages/selectedFiles/selectedFilesView.js
  src/utils/SuccessOutlined.js
  src/utils/anchor.js
  src/utils/classNameConcat.js
  src/utils/createSvgIcon.js
  src/utils/dashboardUtilFunctions.js
  src/utils/formatBytes.js
  src/utils/helpers.js
  src/utils/tables.js
Labels: ✅ Ready for Merge

#231 using about components from bento-tools
  src/pages/about/aboutBodyView.js
  src/pages/about/aboutController.js
  src/pages/about/aboutHeaderView.js
  src/pages/about/aboutView.js
  src/pages/about/xoomInOutView.js
  src/pages/dataDictionary/dataDictonaryView.js
  src/pages/modelPage/modelPageView.js
Labels: ✅ Ready for Merge

#222 update facet filer with multiple sections
  package-lock.json
  package.json
  src/bento/dashboardData.js
  src/components/SideBar/SideBarComponents/FacetFilters.js
  src/components/SideBar/SideBarView.js
  src/themes/dark.js
  src/themes/light.js
Labels: ✋ Don't Merge 🚧
