Repository CBIIT/bento-frontend, pull requests merged in 2022-07, with the labels that each got.

#556 Sys info
  public/injectEnv.js
  src/components/Auth/AuthProvider.js
  src/components/Layout/LayoutView.js
  src/pages/sysInfo/index.js
  src/pages/sysInfo/view.js
  src/utils/graphqlClient.js
Labels: Do not merge

#561 Added nginx for proxy.
  nginx/README.md
  nginx/local-nginx-setup-for-frontend.txt
  nginx/nginx.conf
Labels: enhancement

#577 Merging User Profile Branch into Develop 3.8.0
  src/bento/profileData.js
  src/bento/requestAccessData.js
  src/components/Layout/LayoutView.js
  src/pages/armDetail/armDetailController.js
  src/pages/modelPage/modelPageView.js
  src/pages/profile/components/RoleBadgeGroup.js
  src/pages/profile/components/textEditComponent.js
  src/pages/profile/profileController.js
  src/pages/profile/profileView.js
  src/pages/profile/styles.js
  src/utils/graphqlClient.js
Labels: ✋ Don't Merge 🚧
